name: CI Pipeline for PR

env:
  DISABLE_SWAGGER: "true"

on:
  workflow_dispatch:
  pull_request:

jobs:
  test-and-build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"

      - name: Build the Go application
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.8.12 && swag init
          go get
          CGO_ENABLED=0 go build -o ./test-api
          ls -lah

      - name: Run Go tests
        run: |
          TEST_MODE=true go test ./...

      - name: Fetch all branches
        run: git fetch origin +refs/heads/*:refs/remotes/origin/*

      - name: Get list of changed files
        id: changed-files
        run: |
          echo "$(git diff --name-only origin/${{ github.base_ref }} ${{ github.head_ref }})" > changed-files.txt
          cat changed-files.txt
          
      - name: Filter Go files
        id: filter-go-files
        run: |
          grep '.go$' changed-files.txt > go-files.txt || true
          cat go-files.txt
          echo "CHANGED_GO_FILES=$(cat go-files.txt)" >> $GITHUB_ENV
          
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.58.1

      - name: Run static and security checks
        if: env.CHANGED_GO_FILES != ''
        run: |
          golangci-lint run $(cat go-files.txt)

      - name: Run tests and capture coverage
        if: env.CHANGED_GO_FILES != ''
        run: |
          TEST_MODE=true go test ./... -coverprofile=coverage.out $(cat go-files.txt)
          go tool cover -func=coverage.out