name: CI Pipeline for PR

env:
  DISABLE_SWAGGER: "true"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-and-build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"

      - name: "go build"
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.8.12 && swag init
          go get
          CGO_ENABLED=0 go build -o ./dms-api
          ls -lah
          
      - name: "go test"
        run: |
          TEST_MODE=true go test ./...
          
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.58.1

      - name: "static and security check"
        continue-on-error: true
        run: |
          golangci-lint run ./... --out-format json > golangci-lint-report.json

      - name: Display golangci-lint report
        if: always()
        run: |
          echo "### golangci-lint Report ###"
          cat golangci-lint-report.json

      - name: Run tests and capture coverage
        run: |
          go test ./... -coverprofile=coverage.out
          go tool cover -func=coverage.out

      - name: Display coverage report
        if: always()
        run: |
          echo "### Test Coverage Report ###"
          go tool cover -func=coverage.out

      # Generate reports in Wiki format
      - name: Generate reports in Wiki format
        id: generate-reports
        run: |
          echo "# golangci-lint Report" > golangci-lint-report.wiki
          cat golangci-lint-report.json >> golangci-lint-report.wiki
          echo "" >> golangci-lint-report.wiki
          echo "# Test Coverage Report" > test-coverage-report.wiki
          go tool cover -func=coverage.out >> test-coverage-report.wiki

      # Publish reports to Wiki
      - name: Publish reports to Wiki
        uses: "elstudio/actions-publish-wiki@v1"
        with:
          wiki-pages: |
            golangci-lint-report.wiki
            test-coverage-report.wiki