name: CI Pipeline for PR

env:
  DISABLE_SWAGGER: "true"

on:
  workflow_dispatch:
  pull_request:

jobs:
  test-and-build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"

      - name: Build the Go application
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.8.12 && swag init
          go get
          CGO_ENABLED=0 go build -o ./test-api
          ls -lah
          
      - name: Run Go tests
        run: |
          TEST_MODE=true go test ./...
          
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.58.1

      - name: Run static and security checks
        run: |
          golangci-lint run ./...

      - name: Run tests and capture coverage
        run: |
          go test ./... -coverprofile=coverage.out
          go tool cover -func=coverage.out