name: CI Pipeline for PR

env:
  DISABLE_SWAGGER: "true"

on:
  workflow_dispatch:
  pull_request:

jobs:
  test-and-build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"

      - name: Build the Go application
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.8.12 && swag init
          go get
          CGO_ENABLED=0 go build -o ./test-api
          ls -lah

      - name: Run Go tests
        run: |
          TEST_MODE=true go test -v ./...

      - name: Fetch all branches
        run: git fetch origin +refs/heads/*:refs/remotes/origin/*

      - name: Get list of changed files
        id: changed-files
        run: |
          echo "$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }})" > changed-files.txt
          echo "Changed files"
          cat changed-files.txt
          
      - name: Filter Go files
        id: filter-go-files
        run: |
          grep '.go$' changed-files.txt > go-files.txt || true
          echo "=== Go files ==="
          cat go-files.txt
          echo "CHANGED_GO_FILES=$(cat go-files.txt)" >> $GITHUB_ENV
          
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.58.1

      - name: Run static and security checks
        if: env.CHANGED_GO_FILES != ''
        run: |
          echo "=== Go files ==="
          cat go-files.txt
          golangci-lint run $(cat go-files.txt)

      - name: Run tests on changed files
        run: |
          git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.head_ref }}) | grep '.go$' | xargs go test -coverprofile=coverage.out

      - name: Check coverage threshold
        if: env.CHANGED_GO_FILES != ''
        run: |
          coverage=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | tr -d '%')
          if [ "$coverage" -lt "30" ]; then
            echo "Coverage is below threshold. Current coverage is $coverage%"
            exit 1
          else
            echo "Coverage is above threshold. Current coverage is $coverage%"
          fi