name: CI Pipeline for Report

env:
  DISABLE_SWAGGER: "true"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "setup/**"
  pull_request:
    branches-ignore:
      - "**"

jobs:
  test-and-build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"

      - name: Build the Go application
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.8.12
          swag init
          go get -v
          CGO_ENABLED=0 go build -o ./test-api
          ls -lah

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.58.1

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run static and security checks
        continue-on-error: true
        run: |
          golangci-lint run ./... -v --out-format json > golangci-lint-report.json

      - name: Display golangci-lint report
        if: always()
        run: |
          echo "### golangci-lint Report ###"
          cat golangci-lint-report.json

      - name: Get branch, commit ID, and unique ID
        id: vars
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          commit_id=$(git rev-parse --short HEAD)
          unique_id=$(uuidgen)
          echo "branch=$branch" >> $GITHUB_ENV
          echo "commit_id=$commit_id" >> $GITHUB_ENV
          echo "unique_id=$unique_id" >> $GITHUB_ENV

      - name: Generate MediaWiki report for golangci-lint
        run: |
          echo "'''Report Id:''' ${branch}_${commit_id}_${unique_id}" > static-and-security-check-report.wiki
          .deploy/convert_golangci_lint_to_mediawiki.sh  golangci-lint-report.json >>  static-and-security-check-report.wiki

      - name: Run tests and capture coverage
        run: |
          TEST_MODE=true go test -v ./... -coverprofile=coverage.out

      - name: Display coverage report
        if: always()
        run: |
          echo "### Test Coverage Report ###"
          go tool cover -func=coverage.out >  coverage.txt

      - name: Generate MediaWiki report for test coverage report
        run: |
          echo "'''Report Id:''' ${branch}-${commit_id}-${unique_id}" >  test-coverage-report.wiki
          .deploy/convert_coverage_to_mediawiki.sh  coverage.txt >>  test-coverage-report.wiki

      - name: Update Wiki pages with reports
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "tan.tran@newhorizon-tech.vn"
          git config --global user.name "tan-tran-newhorizon"
          git clone https://${GH_TOKEN}@github.com/tan-tran-newhorizon/golang-project-workflow.wiki.git
          cd golang-project-workflow.wiki
          ls -l
          rm -rf golangci-lint-report.wiki
          mv ../static-and-security-check-report.wiki .
          mv ../test-coverage-report.wiki .
          git add static-and-security-check-report.wiki test-coverage-report.wiki
          git commit -m "Update Wiki with static check, security check and test coverage reports"
          git push origin master